mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ngo.urls')),
]

mysite/ngo/urls.py
from django.urls import path, include
from . import views
#from ngo.views import NgoCreate

urlpatterns = [
    path('',views.index,name='index'),
    path('<int:ngo_id>/' ,views.detail ,name='detail'),
    path('signup/',views.signup,name="signup"),
    path('login/',views.login,name="login"),
   # path('add/',NgoCreate.as_view(),name="ngo-add"),
]

mysite/ngo/models.py
from django.db import models
from django.urls import reverse
# from django.contrib.auth.models import User

# Create your models here.
class Ngo(models.Model):
    ngo_name = models.CharField(max_length=250)
    ngo_logo = models.CharField(max_length=500)
    ngo_loc = models.CharField(max_length=500)
    relief_type = models.CharField(max_length=500)
    # created_by=models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.ngo_name+'-'+self.relief_type+'--'+self.ngo_loc
    
    def get_absolute_url(self):
        return reverse('ngo-details',kwargs={'pk':self.pk})

class NgoDetails(models.Model):
    name = models.ForeignKey(Ngo,on_delete=models.CASCADE)
    details = models.TextField(max_length = 5000)
    address = models.TextField(max_length = 5000)

    def __str__(self):
        return self.name

mysite/ngo/views.py
from django.shortcuts import render
from django.http import HttpResponse,Http404
# from django.views.generic.edit import CreateView
# from django.urls import reverse_lazy
from .models import Ngo,NgoDetails

# Create your views here.
def index(request):
    all_ngos=Ngo.objects.all()
    return render(request,'ngo/index.html', {'all_ngos':all_ngos})

def detail(request,ngo_id):
    try:
        ngo=Ngo.objects.get(pk=ngo_id)
    except Ngo.DoesNotExist:
        raise Http404()
    return render(request,'ngo/detail.html', {'ngo':ngo})

def signup(request):
    return render(request,'ngo/signup.html')

def login(request):
    return render(request,'ngo/login.html')

# class NgoCreate(CreateView):
#     model=Ngo
#     fields=['ngo_name','ngo_logo','ngo_loc','relief_type']

#     def form_valid(self,form):
#         form.instance.created_by=self.request.user
#         return super().form_valid(form)

mysite/ngo/templates/ngo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Mission Heal</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=IM+Fell+English:400i" rel="stylesheet"> 
  <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet"> 
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-expand-md bg-success navbar-dark" style="font-family: 'IM Fell English', serif;">
  <a class="navbar-brand" href="#" style="font-size:1.5em;font-family: 'Permanent Marker', cursive;">Mission Heal</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-left" id="collapsibleNavbar" style="font-size:1.5em;">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link active" href="#">DashBoard</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Form An NGO</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Connect</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="login/">Login</a>
        </li> 
        <li class="nav-item">
            <a class="nav-link" href="signup/">SignUp</a>
          </li>   
    </ul>
  </div>  
</nav>



{% block content%}
{% endblock %}

</body>
</html>

mysite/ngo/templates/ngo/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>DashBoard</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" herf="main.css">
  <link href="https://fonts.googleapis.com/css?family=IM+Fell+English:400i" rel="stylesheet"> 
  <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet"> 
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>
<body>

    <nav class="navbar navbar-expand-md bg-success navbar-dark" style="font-family: 'IM Fell English', serif;">
        <a class="navbar-brand" href="#" style="font-size:1.5em;font-family: 'Permanent Marker', cursive;">Mission Heal</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-left" id="collapsibleNavbar" style="font-size:1.5em;">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" href="#">DashBoard</a>
            </li> 
            <li class="nav-item">
              <a class="nav-link" href="#">Form An NGO</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Connect</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="login/">Login</a>
              </li> 
              <li class="nav-item">
                  <a class="nav-link" href="signup/">SignUp</a>
                </li>    
          </ul>
        </div>  
      </nav>

{% block content %}
{% for n in ngo.ngodetails_set.all %}
<div class="container-fluid">
    <div class="row">
        <h3>Name:</h3>
        <h2>{{ngo.ngo_name}}</h2>
    </div>
    <div class="row">
            <img src="{{ngo.ngo_logo}}" width="400px" height="400px"/>
    </div>
    <div class="row">
        <h3>Details:</h3>
        <br/>
        <p>{{n.details}}</p>
    </div>
    <div class="row">
        <h3>Address:</h3>
        <br/>
        <p>{{n.address}}</p>
    </div>
</div>
{% endfor %}
</body>
</html>
{% endblock %}

mysite/ngo/templates/ngo/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>DashBoard</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=IM+Fell+English:400i" rel="stylesheet"> 
  <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-md bg-success navbar-dark" style="font-family: 'IM Fell English', serif;">
        <a class="navbar-brand" href="#" style="font-size:1.5em;font-family: 'Permanent Marker', cursive;">Mission Heal</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-left" id="collapsibleNavbar" style="font-size:1.5em;">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" href="#">DashBoard</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="add/">Form An NGO</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Connect</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="login/">Login</a>
              </li> 
              <li class="nav-item">
                  <a class="nav-link" href="signup/">SignUp</a>
                </li>    
          </ul>
        </div>  
      </nav>
           
{% block content %}
{% if all_ngos %}

<div class="container-fluid grid-container">
    <br>
    <div class="row text-center">
    {% for ngo in all_ngos %}
    <div class="col-lg-3 text-center">
    <div class="card text-center grid-item" style="max-height:700px">
        <h2 class="text-center">{{ngo.ngo_name}}</h2>
        <img class="card-img-top" src="{{ngo.ngo_logo}}" alt="Card image" style="width:100%">
            <div class="card-body">
                <h4 class="card-title">{{ngo.ngo_name}}</h4>
                <p class="card-text">{{ngo.ngo_loc}}</p>
                <a href="{{ngo.id}}" class="btn btn-primary">View Details</a>
            </div>
    </div>
    </div>
    </div>
</div>
<br>
{% endfor %}

{% else%}
<h3>No Ngo</h3>
{%endif%}
{% endblock %}
</body>
</html>

mysite/ngo/templates/ngo/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Login</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=IM+Fell+English:400i" rel="stylesheet"> 
  <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>
<body>

        <nav class="navbar navbar-expand-md bg-success navbar-dark" style="font-family: 'IM Fell English', serif;">
                <a class="navbar-brand" href="#" style="font-size:1.5em;font-family: 'Permanent Marker', cursive;">Mission Heal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-left" id="collapsibleNavbar" style="font-size:1.5em;">
                  <ul class="navbar-nav">
                    <li class="nav-item">
                      <a class="nav-link active" href="#">DashBoard</a>
                    </li> 
                    <li class="nav-item">
                      <a class="nav-link" href="#">Form An NGO</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Connect</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="login/">Login</a>
                      </li> 
                      <li class="nav-item">
                          <a class="nav-link" href="signup/">SignUp</a>
                        </li>    
                  </ul>
                </div>  
              </nav>
              
              

  <div class="container-fluid">
  <h2>Login</h2>
  <form action="index.html">
    <div class="form-group">
      <label for="email">Email:</label>
      <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
    </div>
    <div class="form-group">
      <label for="pwd">Password:</label>
      <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pswd">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>

</body>
</html>

mysite/ngo/templates/ngo/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Sign Up</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=IM+Fell+English:400i" rel="stylesheet"> 
  <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>
<body>

        <nav class="navbar navbar-expand-md bg-success navbar-dark" style="font-family: 'IM Fell English', serif;">
                <a class="navbar-brand" href="#" style="font-size:1.5em;font-family: 'Permanent Marker', cursive;">Mission Heal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-left" id="collapsibleNavbar" style="font-size:1.5em;">
                  <ul class="navbar-nav">
                    <li class="nav-item">
                      <a class="nav-link active" href="#">DashBoard</a>
                    </li>
                  </ul> 
               </div>
               <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar" style="font-size:1.5em;">
                  <ul class="navbar-nav"> 
                    <li class="nav-item">
                      <a class="nav-link" href="#">Form An NGO</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Connect</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="login/">Login</a>
                      </li> 
                      <li class="nav-item">
                          <a class="nav-link" href="signup/">SignUp</a>
                        </li>    
                  </ul>
                </div>  
              </nav>
              
              

              <div class="container-fluid">
  <h2>Sign Up</h2>
  <form action="index.html">
        <div class="form-group">
                <label for="name">Name:</label>
                <input type="text" class="form-control" id="name" placeholder="Enter name" name="name">
              </div>
    <div class="form-group">
      <label for="email">Email:</label>
      <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
    </div>
    <div class="form-group">
      <label for="pwd">Password:</label>
      <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pswd">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>

</body>
</html>